### ISSUE TITLE
undefined method `id' for #<Contact:...> when you go to contact page

### ISSUE THREAD

**Issue by TylerRick** [gdagley/basejumper#1]
Rails' dom_id method references record.id, which ActiveForm does not provide. I assume this is a bug with ActiveForm. I cannot understand why it would not provide an id method.

My solution was to simply add this:

vendor/plugins/active_form/lib/active_form.rb
-  def id
-    nil
-  end

Can someone else please confirm that this is an issue and a solution?

**Comment by gdagley** [comment]
This appears to be an issue with Ruby 1.9.  I do not see this with Ruby 1.8.6.  I need to take a look at Ruby 1.8.7 to see if it is a problem there.  I have been considering looking for an alternative to the active_form solution for contact forms, this may be a good prompt.

**Comment by TylerRick** [comment]
I think I just figured out why it was only working with 1.8.x. Because ActiveForm objects didn't define an id method, that messaged ended up being handled by Object#id, which has been deprecated since 1.8.x and is now finally removed in 1.9.

> ruby1.8 -e 'puts nil.id'
> -e:1: warning: Object#id will be deprecated; use Object#object_id
> 4
> 
> ruby1.9.1 -e 'puts nil.id'
> -e:1:in `<main>': undefined method`id' for nil:NilClass (NoMethodError)

Cool, well I'll be interested to see what you come up with as a replacement for active_form if you do. In the meantime, I'm happy to keep using it. I'll submit a ticket on the active_form tracker.

**Comment by gdagley** [comment]
I created another gem, validatable_form, that uses the validatable gem for its validations instead of trying to hack in the AR validations.  Feels cleaner and easier to maintain.  It looks like the app now works on Ruby 1.9.

**Comment by gdagley** [comment]
Except for ActiveScaffold.  But that is an upgrade for another day.

**Comment by gdagley** [comment]
I have upgraded ActiveScaffold and Rails to be Ruby 1.9 compatable.
